### ISSUE TITLE
the parse.py seems work wrong

### ISSUE THREAD

**Issue by yyqyu** [seonon/knockdown#1]
hi, as i have tested to have a transfer txt2js, but there is problem isseued:
-bash-4.2# python parse.py 7300.txt res.js
Traceback (most recent call last):
  File "parse.py", line 74, in <module>
    main(args.rawfile, args.output, args.answer_sheet)
  File "parse.py", line 24, in main
    for line in f:
  File "/usr/lib64/python2.7/codecs.py", line 296, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

my txt construction as follow:
1.下列不属于补充运行的是 A.使用最大起飞全重超过5700千克的多发飞机实施的定期载客运输飞行 B.使用最大商载超过3400千克的多发飞机实施的全货物运输飞行 C.使用旅客座位数超过30座或者最大商载超过3400千克的多发飞机实施的不定期载客运输飞行 A

**Comment by seonon** [comment]
有可能是文件编码问题。你试试将文件另存为utf-8编码。

**Comment by yyqyu** [comment]
我用ansi编码能转换 转换后再把js转成utf8才搞定

发自我的 iPhone

在 2019年10月25日，17:16，Xu Seonon <notifications@github.com<mailto:notifications@github.com>> 写道：


有可能是文件编码问题。你试试将文件另存为utf-8编码。
